export default {
  key: "externalLinkaaa",
  name: "外链",
  text: "外链添加添加小组件添加小组件小组件添加小组件添加小组件",
  data: {
    widgetName: "外链",
    protocol: "",
    src: "",
    bgColor: "",
    iconType: "online",
    onlineIcon: "",
    pureIcon: "",
    localIcon: "",
  },
  sizes: {
    "1:1": { widgetName: "外链1" },
    "1:2": { widgetName: "外链2", },
    "2:1": { widgetName: "外链3", },
    "3:2": { widgetName: "外链4", },
    "2:3": { widgetName: "外链5", },
    "3:3": { widgetName: "外链6", },
    "4:3": { widgetName: "外链7", },
    "4:2": { widgetName: "外链8", },
  },
};
